---
title: 'R4DS: Chapter 6'
author: "Brandon Foltz"
date: "2023-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
```{r}
table1
table2
table3
```

```{r rate_per_10000}
table1|>
  mutate(rate = cases / population * 10e3)
```

```{r cases_per_year}
table1|>
  count(year, wt = cases)
```
```{r}
table1|>
  ggplot(aes(x = year, y = cases)) +
  geom_line(aes(group = country), color = "grey50") +
  geom_point(aes(color = country, shape = country)) +
  scale_x_continuous(breaks = c(1999,2000))
```
```{r}
billboard_tidy <- billboard|>
  pivot_longer(
    cols = starts_with("wk"),
    names_to = "week",
    values_to = "rank",
    values_drop_na = TRUE
  )|>
  mutate(
    week = parse_number(week)
  )
```
```{r}
billboard_tidy|>
  ggplot(aes(x = week, y = rank, group = track)) +
  geom_line(alpha = 1/3) +
  scale_y_reverse()
```

```{r}
who2|>
  pivot_longer(
    cols = !(country:year),
    names_to = c("diagnosis", "gender", "age"),
    names_sep = "_",
    values_to = "count"
  )
```
```{r}
household

household|>
  pivot_longer(
    cols = !family,
    names_to = c(".value", "child"),
    names_sep = "_",
    values_drop_na = TRUE
  ) |>
  mutate(
    child = parse_number(child)
  )
```
Pivoting with names_to = c(".value", "id") splits the column names into two components: the first part determines the output column name (x or y), and the second part determines the value of the id column.

6.4 Widening data
https://r4ds.hadley.nz/data-tidy.html#widening-data

```{r}
cms_patient_experience

cms_patient_experience|>
  distinct(measure_cd, measure_title)

cms_patient_experience|>
  pivot_wider(
    id_cols = starts_with("org"),
    names_from = measure_cd,
    values_from = prf_rate
  )
```


