---
title: 'R4DS: Chapter 11'
author: "Brandon Foltz"
date: "2023-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(hexbin)
library(tidymodels)
```

```{r}
ggplot(diamonds,
       aes(x = carat)) +
  geom_histogram(binwidth = 0.5)
```

```{r}
smaller <- diamonds |>
  filter(carat < 3)

ggplot(smaller,
       aes(x = carat)) +
  geom_histogram(binwidth = 0.01)
```
```{r}
ggplot(faithful,
       aes(x = eruptions)) +
  geom_histogram(binwidth = 0.25)
```

```{r}
ggplot(diamonds,
       aes(x = y)) +
  geom_histogram(binwidth = 0.5)
```

```{r}
ggplot(diamonds,
       aes(x=y)) +
  geom_histogram(binwidth = 0.5) +
  coord_cartesian(ylim = c(0,50))

unusual <- diamonds|>
  filter(y < 3 | y > 20)|>
  select(price, x, y, z)|>
  arrange(y)
unusual
```
Replace unusual values with NA, do not drop them.

```{r}
diamonds2 <- diamonds|>
  mutate(y = if_else(y < 3 | y > 20, NA, y))
```

```{r}
ggplot(diamonds2,
       aes(x=x, y=y)) +
  geom_point()
```

```{r}
nycflights13::flights|>
  mutate(
    cancelled = is.na(dep_time),
    sched_hour = sched_dep_time %/% 100,
    sched_min = sched_dep_time %% 100,
    sched_dep_time = sched_hour + (sched_min / 60)
  )|>
  ggplot(aes(x = sched_dep_time)) +
  geom_freqpoly(aes(color = cancelled), binwidth = 1/4)
```

11.5 Covariation
https://r4ds.hadley.nz/eda#covariation

```{r}
ggplot(diamonds,
       aes(x = price)) +
  geom_freqpoly(aes(color = cut), binwidth = 500, linewidth = 0.75)
```

To make the comparison easier we need to swap what is displayed on the y-axis. Instead of displaying count, we’ll display the density, which is the count standardized so that the area under each frequency polygon is one.

```{r}
ggplot(diamonds,
       aes(x = price, y = after_stat(density))) +
  geom_freqpoly(aes(color = cut), binwidth = 500, linewidth = 0.75)
```

```{r}
ggplot(diamonds,
       aes(x = cut, y = price)) +
  geom_boxplot() +
  coord_flip()
```

```{r}
ggplot(mpg,
       aes(x = class, y = hwy)) +
  geom_boxplot() +
  coord_flip()
```

```{r}
ggplot(mpg,
       aes(x = fct_reorder(class, hwy, median), y = hwy)) +
  geom_boxplot() +
  coord_flip()
```

Two categorical vars

```{r}
ggplot(diamonds,
       aes(x = cut, y = color)) +
  geom_count()
```

```{r}
diamonds|>
  count(color, cut)

diamonds|>
  count(color, cut)|>
  ggplot(aes(x = color, y = cut)) +
  geom_tile(aes(fill = n))
```

Two numeric vars

```{r}
ggplot(diamonds,
       aes(x = carat, y = price)) +
  geom_point()

ggplot(diamonds,
       aes(x = carat, y = price)) +
  geom_point(alpha = 1/100, color = "black")

ggplot(diamonds,
       aes(x = carat, y = price)) +
  geom_jitter(color = "dodgerblue")
```

```{r}
ggplot(smaller,
       aes(x = carat, y = price)) +
  geom_bin2d()

ggplot(smaller,
       aes(x = carat, y = price)) +
  geom_hex()
```

```{r}
ggplot(smaller,
       aes(x = carat, y = price)) +
  geom_boxplot(aes(group = cut_width(carat, 0.1)))

ggplot(smaller,
       aes(x = carat, y = price)) +
  geom_boxplot(aes(group = cut_number(carat, 20)))
```

```{r}
ggplot(faithful,
       aes(x = eruptions, y = waiting)) +
  geom_point()
```

Models

```{r}
diamonds <- diamonds|>
  mutate(
    log_price = log(price),
    log_carat = log(carat)
  )

diamonds_fit <- linear_reg() |>
  fit(log_price ~ log_carat, data = diamonds)

diamonds_aug <- augment(diamonds_fit, new_data = diamonds)|>
  mutate(.resid = exp(.resid))

ggplot(diamonds_aug, aes(x = carat, y = .resid)) +
  geom_point()
```

```{r}
ggplot(diamonds_aug,
       aes(x = cut, y = .resid)) +
  geom_boxplot()
```

