---
title: 'R4DS: Chapter 15'
author: "Brandon Foltz"
date: "2023-03-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(babynames)
```

```{r}
string1 <- "This is a string"
string2 <- 'If I want to include a "quote" inside a string, I use single quotes.'
```

```{r escapes}
double_quote <- "\""
single_quote <- '\''
backslash <- "\\"
x <- c(single_quote, double_quote, backslash)
x
str_view(x)
```
```{r raw_string}
tricky <- r"(double_quote <- "\"" # or '"' single quote <- '\'' # or "'")"
str_view(tricky)
```
```{r other_special_characters}
x <- c("one\ntwo", "one\ttwo", "\u00b5", "\U0001f604")
x
str_view(x)
```

```{r str_c}
str_c("x","y")
str_c("x","y","z")
str_c("Hello ", c("John", "Susan"))
```
```{r}
df <- tibble(name = c("Flora", "David", "Terra", NA))
df|>
  mutate(greeting = str_c("Hi, ", name, "!"))

df|>
  mutate(
    greeting1 = str_c("Hi, ", coalesce(name, "you"), "!"),
    greeting2 = coalesce(str_c("Hi, ", name, "!"), "Hi!")
  )
```
```{r str_glue}
df |>
  mutate(greeting = str_glue("Hi, {name}!"))

df|>
  mutate(greeting = str_glue("{{Hi, {name}!}}"))
```
```{r}
str_flatten(c("x", "y", "z"))
str_flatten(c("x", "y", "z"), ", ")
str_flatten(c("x", "y", "z"), ", ", last = ", and ")
```

```{r}
df <- tribble(
  ~ name, ~ fruit,
  "Carmen", "banana",
  "Carmen", "apple",
  "Marvin", "nectarine",
  "Terence", "cantaloupe",
  "Terence", "papaya",
  "Terence", "mandarin"
)

df|>
  group_by(name)|>
  summarise(fruits = str_flatten(fruit, ", "))
```

Extracting data from strings
df |> separate_longer_delim(col, delim)
df |> separate_longer_position(col, width)
df |> separate_wider_delim(col, delim, names)
df |> separate_wider_position(col, widths)

```{r separate_into_rows}
df1 <- tibble(x = c("a", "b","c", "d,e", "f"))
df1|>
  separate_longer_delim(x, delim = ",")

df2 <- tibble(x = c("1211", "131", "21"))
df2|>
  separate_longer_position(x, width = 1)
```

```{r separate_into_columns}
df3 <- tibble(x = c("a10.1.2022", "b10.2.2011", "e15.1.2015"))
df3|>
  separate_wider_delim(
    x,
    delim = ".",
    names = c("code", "edition", "year")
  )

df3|>
  separate_wider_delim(
    x,
    delim = ".",
    names = c("code", NA, "year")
  )

df4 <- tibble(x = c("202215TX", "202122LA", "202325CA"))
df4|>
  separate_wider_position(
    x,
    widths = c(year = 4, age = 2, state = 2)
  )
```
```{r widen_issues}
df <- tibble(x = c("1-1-1", "1-1-2", "1-3", "1-3-2", "1"))
df|>
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z"),
    too_few = "debug"
  )

df|>
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x","y","z"),
    too_few = "align_start"
  )

df <- tibble(x = c("1-1-1", "1-1-2", "1-3-5-6", "1-3-2", "1-3-5-7-9"))

df |> 
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z")
  )

debug <- df |> 
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z"),
    too_many = "debug"
  )

debug |> filter(!x_ok)

df |> 
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z"),
    too_many = "drop"
  )


df |> 
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z"),
    too_many = "merge"
  )
```

15.5.1 Letters

```{r length}
str_length(c("a", "R for data science", NA))

babynames|>
  count(length = str_length(name), wt = n)

babynames|>
  filter(str_length(name) == 15)|>
  count(name, wt = n, sort = TRUE)
```

```{r subsetting}
x  <- c("Apple", "Banana", "Pear")
str_sub(x, 1, 3)
str_sub(x, -3, -1)
str_sub("a", 1, 5)

babynames|>
  mutate(
    first = str_sub(name, 1, 1),
    last = str_sub(name, -1, -1)
  )
```
```{r}
str_to_upper(c("Apple", "Banana", "Pear"))
str_to_lower(c("Apple", "Banana", "Pear"))
str_sort(c("Apple", "Banana", "Pear"))
```

