---
title: 'R4DS: Chapter 17'
author: "Brandon Foltz"
date: "2023-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
Factor Basics

```{r}
x1 <- c("Dec", "Apr", "Jan", "Mar") #poopoo
x2 <- c("Dec", "Apr", "Jam", "Mar")

month_levels <- c(
  "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
)
y1 <- factor(x1, levels = month_levels)
y1
sort(y1)
y2 <- fct(x2, levels = month_levels)
y2

factor(x1)
fct(x1)

levels(y2)

csv <- "
month, value
Jan, 12
Feb, 56
Mar, 12
"

df <- read_csv(csv, col_types = cols(month = col_factor(month_levels)))
df$month
```

GSS

```{r}
gss_cat|>
  count(race)
```
```{r}
relig_summary <- gss_cat|>
  group_by(relig)|>
  summarise(
    tvhours = mean(tvhours, na.rm = TRUE),
    n = n()
  )

ggplot(relig_summary,
       aes(x = tvhours, y = relig)) +
  geom_point()

ggplot(relig_summary,
       aes(x = tvhours, y = fct_reorder(relig, tvhours))) +
  geom_point()

relig_summary|>
  mutate(
    relig = fct_reorder(relig, tvhours)
  )|>
  ggplot(aes(x = tvhours, y = relig)) +
  geom_point()

rincome_summary <- gss_cat|>
  group_by(rincome)|>
  summarise(
    age = mean(age, na.rm = TRUE),
    n = n()
  )

  ggplot(rincome_summary,
         aes(x = age, y = fct_reorder(rincome, age))) +
  geom_point()
  
ggplot(rincome_summary,
       aes(x = age, y = fct_relevel(rincome, "Not applicable"))) +
  geom_point()
```

```{r}
by_age <- gss_cat|>
  filter(!is.na(age)) |>
  count(age, marital)|>
  group_by(age)|>
  mutate(
    prop = n / sum(n)
  )

ggplot(by_age,
       aes(x = age, y = prop, color = marital)) +
  geom_line(linewidth = 1) +
  scale_color_brewer(palette = "Set1")

ggplot(by_age,
       aes(x = age, y = prop, color = fct_reorder2(marital, age, prop))) +
  geom_line(linewidth = 1) +
  scale_color_brewer(palette = "Set1") +
  labs(color = "marital")
```
```{r}
gss_cat|>
  mutate(marital = marital |>
  fct_infreq()|>
  fct_rev())|>
  ggplot(aes(x = marital)) +
  geom_bar()
```

Modifying Levels

```{r}
gss_cat|>
  count(partyid)

gss_cat |>
  mutate(
    partyid = fct_recode(partyid,
      "Republican, strong"    = "Strong republican",
      "Republican, weak"      = "Not str republican",
      "Independent, near rep" = "Ind,near rep",
      "Independent, near dem" = "Ind,near dem",
      "Democrat, weak"        = "Not str democrat",
      "Democrat, strong"      = "Strong democrat"
    )
  ) |>
  count(partyid)
```

```{r}
gss_cat |>
  mutate(
    partyid = fct_recode(partyid,
      "Republican, strong"    = "Strong republican",
      "Republican, weak"      = "Not str republican",
      "Independent, near rep" = "Ind,near rep",
      "Independent, near dem" = "Ind,near dem",
      "Democrat, weak"        = "Not str democrat",
      "Democrat, strong"      = "Strong democrat",
      "Other"                 = "No answer",
      "Other"                 = "Don't know",
      "Other"                 = "Other party"
    )
  ) |>
  count(partyid)
```

```{r}
gss_cat |>
  mutate(
    partyid = fct_collapse(partyid,
      "other" = c("No answer", "Don't know", "Other party"),
      "rep" = c("Strong republican", "Not str republican"),
      "ind" = c("Ind,near rep", "Independent", "Ind,near dem"),
      "dem" = c("Not str democrat", "Strong democrat")
    )
  ) |>
  count(partyid)
```
 Factor Lumps
 
```{r}
gss_cat|>
  mutate(relig = fct_lump_lowfreq(relig))|>
  count(relig)

gss_cat|>
  mutate(relig = fct_lump_n(relig, n = 10))|>
  count(relig, sort = TRUE)|>
  print(n = Inf)
```
Ordered factors

```{r}
ordered(c("a","b","c"))
```

