---
title: 'R4DS: Hierarchical Date'
author: "Brandon Foltz"
date: "2023-03-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(repurrrsive)
library(jsonlite)
```

```{r}
x1 <- list(1:4, "a", TRUE)
x1[[1]]

x2 <- list(a = 1:2, b = 1:3, c=1:4)
x2

str(x1)
str(x2)
```
Hierarchy

```{r}
x3 <- list(list(1,2), list(3,4))
str(x3)
x4 <- c(list(1,2), list(3,4))
str(x4)
x5 <- list(1, list(2, list(3, list(4, list(5)))))
x5

View(x4)
```

Lists in tibbles

```{r}
df <- tibble(
  x = 1:2,
  y = c("a", "b"),
  z = list(list(1,2), list(3,4,5))
)
df
View(df)

df|>
  filter(x == 1)
```
```{r}
data.frame(x = list(1:3, 3:5))

data.frame(
  x = I(list(1:2, 3:5)),
  y = c("1,2,3,4,5")
)
```
Unnesting

```{r}
df1 <- tribble(
  ~x, ~y,
  1, list(a = 11, b = 12),
  2, list(a = 21, b = 22),
  3, list(a = 31, b = 32),
)
df

df2 <- tribble(
  ~x, ~y,
  1, list(11,12,13),
  2, list(21),
  3, list(31,32)
)
```

```{r}
df1|>
  unnest_wider(y)

df1|>
  unnest_wider(y, names_sep = "_")
```

```{r}
df2 |>
  unnest_longer(y)
```

```{r}
df6 <- tribble(
  ~x, ~y,
  "a", list(1,2),
  "b", list(3),
  "c", list()
)

df6|>
  unnest_longer(y, keep_empty = TRUE)
```

Inconsistent Types

```{r}
df4 <- tribble(
  ~x, ~y,
  "a", list(1),
  "b", list("a", TRUE, 5)
)

df4|>
  unnest_longer(y)
```

Case Studies
Very Wide Data

```{r}
repos <- tibble(json = gh_repos)
repos

repos|>
  unnest_longer(json)

repos|>
  unnest_longer(json)|>
  unnest_wider(json)

repos|>
  unnest_longer(json)|>
  unnest_wider(json)|>
  names()|>
  head(10)

repos|>
  unnest_longer(json)|>
  unnest_wider(json)|>
  select(id, full_name, owner, description)

repos|>
  unnest_longer(json)|>
  unnest_wider(json)|>
  select(id, full_name, owner, description)|>
  unnest_wider(owner, names_sep = "_")
```

Relational Data

```{r}
chars <- tibble(json = got_chars)
chars

chars|>
  unnest_wider(json)

characters <- chars|>
  unnest_wider(json)|>
  select(id, name, gender, culture, born, died, alive)
characters
View(characters)
```

```{r}
chars|>
  unnest_wider(json)|>
  select(id, where(is.list))

chars |>
  unnest_wider(json)|>
  select(id, titles)|>
  unnest_longer(titles)

titles <- chars|>
  unnest_wider(json)|>
  select(id, titles)|>
  unnest_longer(titles)|>
  filter(titles != "")|>
  rename(title = titles)
titles
```

Deeply Nested

```{r}
gmaps_cities

gmaps_cities|>
  unnest_wider(json)

gmaps_cities|>
  unnest_wider(json)|>
  select(-status)|>
  unnest_longer(results)

locations <- gmaps_cities|>
  unnest_wider(json)|>
  select(-status)|>
  unnest_longer(results)|>
  unnest_wider(results)

locations|>
  select(city, formatted_address, geometry)|>
  unnest_wider(geometry)

locations|>
  select(city, formatted_address, geometry)|>
  unnest_wider(geometry)|>
  unnest_wider(location)

locations|>
  select(city, formatted_address, geometry)|>
  unnest_wider(geometry)|>
  select(!location:viewport)|>
  unnest_wider(bounds)

locations|>
  select(city, formatted_address, geometry)|>
  unnest_wider(geometry)|>
  select(!location:viewport)|>
  unnest_wider(bounds)|>
  rename(ne = northeast, sw = southwest)|>
  unnest_wider(c(ne, sw), names_sep = "_")

locations|>
  select(city, formatted_address, geometry)|>
  hoist(
    geometry,
    ne_lat = c("bounds", "northeast", "lat"),
    sw_lat = c("bounds", "southwest", "lat"),
    ne_lng = c("bounds", "northeast", "lng"),
    sw_lng = c("bounds", "southwest", "lng")
  )
```

JSON
```{r}
gh_users_json()
gh_users2 <- read_json(gh_users_json())
identical(gh_users, gh_users2)

str(parse_json("1"))
str(parse_json("[1,2,3]"))
str(parse_json('{"x": [1,2,3]}'))
```

```{r}
json <- '[
  {"name": "John", "age": 34},
  {"name": "Susan", "age": 27}
]'

df <- tibble(json = parse_json(json))
df

df|>
  unnest_wider(json)

```

```{r}
json <- '{
  "status": "OK", 
  "results": [
    {"name": "John", "age": 34},
    {"name": "Susan", "age": 27}
 ]
}
'

df <- tibble(json = list(parse_json(json)))
df

df|>
  unnest_wider(json)|>
  unnest_longer(results)|>
  unnest_wider(results)

df <- tibble(results = parse_json(json)$results)
df |> 
  unnest_wider(results)
```

